{inputs, ...}: {
  flake-file.inputs.nixcord = {
    url = "github:FlameFlag/nixcord";
    inputs = {
      nixpkgs.follows = "nixpkgs";
      flake-parts.follows = "flake-parts";
    };
  };
  flake.modules = {
    nixos.discord.home-manager.sharedModules = [
      inputs.nixcord.homeModules.nixcord
      inputs.self.modules.homeManager.discord
    ];
    homeManager.discord.programs.nixcord = {
      enable = true;
      discord.enable = false;
      equibop = {
        enable = true;
        autoscroll.enable = true;
      };
      config = {
        plugins = {
          accountPanelServerProfile.enable = true;
          altKrispSwitch.enable = true;
          alwaysAnimate.enable = true;
          alwaysExpandProfiles.enable = true;
          alwaysExpandRoles.enable = true;
          alwaysTrust.enable = true;
          anammox.enable = true;
          # animalese.enable = true;
          anonymiseFileNames.enable = true;
          atSomeone.enable = true;
          bannersEverywhere.enable = true;
          betterActivities.enable = true;
          betterAudioPlayer.enable = true;
          betterBanReasons.enable = true;
          betterBlockedUsers.enable = true;
          betterCommands.enable = true;
          betterFolders.enable = true;
          betterGifAltText.enable = true;
          betterGifPicker.enable = true;
          betterInvites.enable = true;
          betterNotesBox.enable = true;
          betterRoleContext.enable = true;
          betterRoleDot.enable = true;
          betterSessions.enable = true;
          betterSettings.enable = true;
          betterUploadButton.enable = true;
          # betterUserArea.enable = true; # TODO
          biggerStreamPreview.enable = true;
          callTimer.enable = true;
          channelBadges.enable = true;
          channelTabs.enable = true;
          characterCounter.enable = true;
          # cleanChannelName.enable = true;
          # cleanerChannelGroups.enable = true; # TODO
          ClearURLs.enable = true;
          consoleJanitor.enable = true;
          copyEmojiMarkdown.enable = true;
          copyFileContents.enable = true;
          copyProfileColors.enable = true;
          copyStatusUrls.enable = true;
          copyStickerLinks.enable = true;
          copyUserMention.enable = true;
          CopyUserURLs.enable = true;
          crashHandler.enable = true;
          customIdle.enable = true;
          CustomRPC.enable = true;
          customTimestamps.enable = true;
          decodeBase64.enable = true;
          dearrow.enable = true;
          decor.enable = true;
          disableCallIdle.enable = true;
          discordDevBanner.enable = true;
          # dragFavoriteEmotes.enable = true; # TODO
          # dragify.enable = true;
          equicordToolbox.enable = true;
          experiments.enable = true;
          exportMessages.enable = true;
          expressionCloner.enable = true;
          fakeNitro.enable = true;
          fakeProfileThemes.enable = true;
          favoriteEmojiFirst.enable = true;
          favoriteGifSearch.enable = true;
          # favoriteAnything.enable = true; # TODO
          findReply.enable = true;
          fixCodeblockGap.enable = true;
          fixFileExtensions.enable = true;
          fixImagesQuality.enable = true;
          fixSpotifyEmbeds.enable = true;
          fixYoutubeEmbeds.enable = true;
          forceOwnerCrown.enable = true;
          forwardAnywhere.enable = true;
          frequentQuickSwitcher.enable = true;
          friendCloud.enable = true;
          friendCodes.enable = true;
          friendInvites.enable = true;
          friendshipRanks.enable = true;
          friendsSince.enable = true;
          fullSearchContext.enable = true;
          fullUserInChatbox.enable = true;
          FullVCPFP.enable = true;
          gifPaste.enable = true;
          gifRoulette.enable = true;
          gitHubRepos.enable = true;
          globalBadges.enable = true;
          googleThat.enable = true;
          greetStickerPicker.enable = true;
          guildPickerDumper.enable = true;
          guildTagSettings.enable = true;
          holyNotes.enable = true;
          homeTyping.enable = true;
          iconViewer.enable = true;
          ignoreTerms.enable = true;
          iLoveSpam.enable = true;
          imageFilename.enable = true;
          imageLink.enable = true;
          imgToGif.enable = true;
          implicitRelationships.enable = true;
          inRole.enable = true;
          IRememberYou.enable = true;
          jumpTo.enable = true;
          keepCurrentChannel.enable = true;
          lastActive.enable = true;
          limitMiddleClickPaste.enable = true;
          loadingQuotes.enable = true;
          mediaPlaybackSpeed.enable = true;
          memberCount.enable = true;
          mentionAvatars.enable = true;
          messageClickActions.enable = true;
          messageColors.enable = true;
          messageLinkEmbeds.enable = true;
          messageLinkTooltip.enable = true;
          messageLogger.enable = true; # TODO: remove
          messageLoggerEnhanced.enable = true;
          # messagePeek.enable = true; # TODO
          moreKaomoji.enable = true;
          moreQuickReactions.enable = true;
          moreStickers.enable = true;
          moreUserTags.enable = true;
          MutualGroupDMs.enable = true;
          neverPausePreviews.enable = true;
          newPluginsManager.enable = true;
          noDevtoolsWarning.enable = true;
          noF1.enable = true;
          noModalAnimation.enable = true;
          noNitroUpsell.enable = true;
          noOnboardingDelay.enable = true;
          normalizeMessageLinks.enable = true;
          noUnblockToJump.enable = true;
          oneko.enable = true;
          openInApp.enable = true;
          pauseInvitesForever.enable = true;
          permissionFreeWill.enable = true;
          permissionsViewer.enable = true;
          petpet.enable = true;
          pictureInPicture.enable = true;
          PinDMs.enable = true;
          pingNotifications.enable = true;
          pinIcon.enable = true;
          platformIndicators.enable = true;
          platformSpoofer.enable = true;
          previewMessage.enable = true;
          # profileSets.enable = true; # TODO
          questify.enable = true;
          quickMention.enable = true;
          quickReply.enable = true;
          quoter.enable = true;
          reactErrorDecoder.enable = true;
          readAllNotificationsButton.enable = true;
          RecentDMSwitcher.enable = true;
          relationshipNotifier.enable = true;
          replaceGoogleSearch.enable = true;
          replyPingControl.enable = true;
          replyTimestamp.enable = true;
          revealAllSpoilers.enable = true;
          reverseImageSearch.enable = true;
          ReviewDB.enable = true;
          # richMagnetLinks.enable = true; # TODO
          roleColorEverywhere.enable = true;
          searchFix.enable = true;
          sekaiStickers.enable = true;
          selfForward.enable = true;
          sendTimestamps.enable = true;
          serverInfo.enable = true;
          serverListIndicators.enable = true;
          serverSearch.enable = true;
          shikiCodeblocks.enable = true;
          showAllMessageButtons.enable = true;
          showBadgesInChat.enable = true;
          showConnections.enable = true;
          showHiddenChannels.enable = true;
          showHiddenThings.enable = true;
          showMessageEmbeds.enable = true;
          showMeYourName.enable = true;
          showResourceChannels.enable = true;
          # showSongName.enable = true; TODO
          showTimeoutDuration.enable = true;
          sidebarChat.enable = true;
          silentTyping.enable = true;
          soggy.enable = true;
          songLink.enable = true;
          sortFriendRequests.enable = true;
          soundBoardLogger.enable = true;
          # splitLargeMessages.enable = true;
          spotifyCrack.enable = true;
          startupTimings.enable = true;
          stickerPaste.enable = true;
          summaries.enable = true;
          themeAttributes.enable = true;
          # themeLibrary.enable = true;
          tidalEmbeds.enable = true;
          TiktokTTS.enable = true;
          timezones.enable = true;
          title.enable = true;
          toneIndicators.enable = true;
          translate.enable = true;
          # translate+?
          typingIndicator.enable = true;
          typingTweaks.enable = true;
          unindent.enable = true;
          unitConverter.enable = true; # TODO: metric
          universalMention.enable = true;
          unlimitedAccounts.enable = true;
          unlockedAvatarZoom.enable = true;
          unreadCountBadge.enable = true;
          unsuppressEmbeds.enable = true;
          userMessagesPronouns.enable = true;
          UserPFP.enable = true;
          userVoiceShow.enable = true;
          USRBG.enable = true;
          validReply.enable = true;
          validUser.enable = true;
          VCPanelSettings.enable = true;
          vencordToolbox.enable = true;
          viewIcons.enable = true;
          viewRaw.enable = true;
          viewRawVariant.enable = true;
          voiceButtons.enable = true;
          voiceChatDoubleClick.enable = true;
          voiceChatUtilities.enable = true;
          voiceDownload.enable = true;
          voiceMessages.enable = true;
          # voiceMessageTranscriber.enable = true; # TODO
          # voiceRejoin.enable = true; # TODO
          volumeBooster.enable = true;
          webKeybinds.enable = true;
          webScreenShareFixes.enable = true;
          whoReacted.enable = true;
          whosWatching.enable = true;
          wigglyText.enable = true;
          youtubeAdblock.enable = true;
          youtubeDescription.enable = true;
        };
      };
    };
  };
}
